# Generated by Django 4.2.23 on 2025-06-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="allow_email",
            field=models.BooleanField(
                default=True, help_text="Whether this contact allows receiving emails"
            ),
        ),
    ]
