# Generated by Django 5.2.3 on 2025-06-13 05:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns_api', '0001_initial'),
        ('contacts_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('sent_with_errors', 'Sent with Errors'), ('failed', 'Failed'), ('scheduled', 'Scheduled')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='CampaignAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ses_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('complaint', 'Complaint'), ('rejected', 'Rejected'), ('failed_to_send', 'Failed to Send')], max_length=20)),
                ('event_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='campaigns_api.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_interactions', to='contacts_api.contact')),
            ],
            options={
                'verbose_name': 'Campaign Analytic Event',
                'verbose_name_plural': 'Campaign Analytic Events',
                'ordering': ['-event_timestamp'],
                'indexes': [models.Index(fields=['campaign', 'contact', 'event_type'], name='campaigns_a_campaig_acd89b_idx'), models.Index(fields=['ses_message_id', 'event_type'], name='campaigns_a_ses_mes_da6156_idx')],
            },
        ),
    ]
